services:
  scheduler:
    image: ${IMAGE:-ghcr.io/CHANGE_ME/scheduler:latest}
    container_name: scheduler
    restart: unless-stopped
    ports:
      - "3005:8080"

    labels:
      - "wud.watch=true"